apiVersion: v1
kind: Service
metadata:
  name: blue-green-service
spec:
  type: LoadBalancer
  selector:
    app: blue   # Initially pointing to blue
  ports:
  - port: 80
    targetPort: 8080
# Service is used for traffic switching
