apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
  annotations:
    harness.io/color: primary
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: my-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helper-deployment
  annotations:
    harness.io/direct-apply: "true"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: helper
