apiVersion: v1
kind: Service
metadata:
  name: blue-green-service
spec:
  type: LoadBalancer
  selector:
    app: blue
    harness.io/color: primary  # Required for Blue-Green Deployment
  ports:
    - port: 80
      targetPort: 8080
 # Service is used for traffic switching
