apiVersion: v1
kind: Service
metadata:
  name: blue-green-service-stage
spec:
  type: LoadBalancer
  selector:
    app: green
    harness.io/color: stage  # Required for Blue-Green Deployment
  ports:
    - port: 80
      targetPort: 8080
