apiVersion: apps/v1
kind: Deployment
metadata:
  name: canary-deployment
  labels:
    app: canary
spec:
  replicas: 4  # Total number of replicas to be deployed in phases
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1   # Maximum number of additional pods during an update
      maxUnavailable: 0  # Ensures no downtime
  selector:
    matchLabels:
      app: canary
  template:
    metadata:
      labels:
        app: canary
        harness.io/color: canary  # Used for distinguishing the canary version
    spec:
      containers:
        - name: hello-app
          image: gcr.io/google-samples/hello-app:2.0  # Canary version
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: canary-service
  labels:
    app: canary
spec:
  selector:
    app: canary  # Targets pods with this label
  ports:
    - protocol: TCP
      port: 80      # Exposes the service on port 80
      targetPort: 8080  # Maps to the container port
  type: LoadBalancer  # Exposes the service externally
