apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app-deployment
  namespace: autopilot-cluster-sm  # Use your cluster namespace
  labels:
    app: demo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
        - name: demo-app
          image: "sushma-sm/demo-app"  # Your Docker image repo
          ports:
            - containerPort: 80
