apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app-deployment
  namespace: autopilot-cluster-sm  # Ensure this namespace exists in GKE
  labels:
    app: demo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
        - name: demo-app
          image: "sushmamounika/my-repo-sm:latest"  # Updated Docker image repo
          imagePullPolicy: IfNotPresent  # Ensures it doesn't pull unnecessarily
          ports:
            - containerPort: 80
