apiVersion: v1
kind: Service
metadata:
  name: demo-app-service
  namespace: autopilot-cluster-sm  # Use your cluster namespace
spec:
  selector:
    app: demo-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer  # GKE will create an external LoadBalancer
