replicaCount: 2

image:
  repository: sushma-sm/demo-app
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80
  targetPort: 80

namespace: autopilot-cluster-sm  # Your GKE Namespace
